### ISSUE TITLE
Not-responsive on Debian 10 32 bit

### ISSUE THREAD

**Issue by 3ruce** [raoofha/gter#1]
So I installed this after a `sudo apt install xserver-xephyr` on Debian 10 32 bit, the script opened a terminal but I couldn't enter a command to load anything....

**Comment by raoofha** [comment]
for a quick workaround I think you need to select the command line at the bottom of the window with mouse until I fix this. notice that gter is in early stages

**Comment by 3ruce** [comment]
Ok, cool, I'll take a look, btw, what was the motivation for this project?

**Comment by raoofha** [comment]
I think it's cool to have a unified UI to the OS it's like you're chatting with the OS and it/(she/he in the future) can show/ask you anything in response. my core idea is to make it easy to create something like Mathematica or Jupyter(IPython) by creating set of tiny GUI program that follow the same convention to talk to each other something like [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) for GUI apps, on [HN](https://news.ycombinator.com/item?id=22044368) people commented about Rhino and Autocad combining CLI and GUI that I think is very cool.

**Comment by 3ruce** [comment]
Nice, yeah... I've been mulling over different window managers aside from Xfce's default... i3 and so on, but I also wanted to try this as a way to put a browser, likekly Qutebrowser into a tmux window... I'd also like Qutebrowser to show the time in it's status bar, but that's something for another day...

**Comment by raoofha** [comment]
oh Gter is not a virtual terminal it's actually a window manager so you can't use it like that but you can ssh to your server and use ssh X11 forwarding to open the browser.

**Comment by 3ruce** [comment]
Ok, cool...

**Comment by raoofha** [comment]
please test the new version and let me know if there is any problem.
